process.env.NODE_ENV = 'test'
process.env.DATABASE_URL = process.env.DATABASE_URL ?? 'postgresql://user:pass@localhost:5432/test'
process.env.REDIS_URL = process.env.REDIS_URL ?? 'redis://localhost:6379'
process.env.JWT_SECRET =
  process.env.JWT_SECRET ?? 'test-secret-test-secret-test-secret-123456'
process.env.APP_URL = process.env.APP_URL ?? 'https://app.example.test'
process.env.TOTP_ENCRYPTION_KEY =
  process.env.TOTP_ENCRYPTION_KEY ?? '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
process.env.R2_ACCOUNT_ID = process.env.R2_ACCOUNT_ID ?? 'test-account'
process.env.R2_ACCESS_KEY_ID = process.env.R2_ACCESS_KEY_ID ?? 'test-access-key'
process.env.R2_SECRET_ACCESS_KEY = process.env.R2_SECRET_ACCESS_KEY ?? 'test-secret-key'
process.env.R2_BUCKET_NAME = process.env.R2_BUCKET_NAME ?? 'test-bucket'
process.env.R2_PUBLIC_URL = process.env.R2_PUBLIC_URL ?? 'https://r2.example.test'
process.env.STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY ?? 'sk_test_dummy'
process.env.STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET ?? 'whsec_dummy'
process.env.STRIPE_PRICE_MONTHLY = process.env.STRIPE_PRICE_MONTHLY ?? 'price_monthly'
process.env.STRIPE_PRICE_ANNUAL = process.env.STRIPE_PRICE_ANNUAL ?? 'price_annual'
process.env.STRIPE_PRICE_GEO_1K = process.env.STRIPE_PRICE_GEO_1K ?? 'price_geo_1k'
process.env.STRIPE_PRICE_GEO_5K = process.env.STRIPE_PRICE_GEO_5K ?? 'price_geo_5k'
process.env.STRIPE_PRICE_GEO_10K = process.env.STRIPE_PRICE_GEO_10K ?? 'price_geo_10k'
process.env.STRIPE_PRICE_GEO_25K = process.env.STRIPE_PRICE_GEO_25K ?? 'price_geo_25k'
